[tool.pylint.MAIN]
extension-pkg-allow-list = "pygame"
load-plugins = [
  "pylint.extensions.code_style",
  "pylint.extensions.typing",
  "pylint_strict_informational",
]

[tool.pylint.messages_control]
max-line-length = 88

disable = [
    "too-few-public-methods",
    "too-many-arguments",
    "protected-access",
    "too-many-locals",
    "fixme",
]

[tool.pylint.design]
max-returns = 8

[tool.yapf]
column_limit = 88
split_before_dot = true
split_before_first_argument = true
dedent_closing_brackets = true

[tool.isort]
line_length = 88
combine_as_imports = true
length_sort = true
order_by_type = true

[tool.docformatter]
recursive = true
wrap-summaries = 88
wrap-descriptions = 88
